# LAB 02 – LÀM QUEN VỚI PYTORCH

## Bài 1. Tạo Tensor cơ bản

In [ ]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)
print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32

## Bài 2. Tạo các Tensor thường dùng

In [ ]:
import torch

torch.manual_seed(42)

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
f = torch.full((5, 5), 10)

print("rand:")
print(a)
print("randn:")
print(b)
print("zeros:")
print(c)
print("ones:")
print(d)
print("eye:")
print(e)
print("Tensor 5x5 toàn 10:")
print(f)


rand:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
randn:
tensor([[ 2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898],
        [-0.9890,  0.9580,  1.3221,  0.8172]])
zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
eye:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Tensor 5x5 toàn 10:
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

## Bài 3. Kiểm tra thông tin Tensor

In [ ]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)



Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32

## Bài 4. Slicing và Indexing

In [ ]:
import torch

torch.manual_seed(42)
a = torch.randn(3, 4, 5)

print("Shape của a:", a.shape)
print("Shape của a[1]:", a[1].shape)
print("Shape của a[1:, 2:4]:", a[1:, 2:4].shape)

# Hai phần tử cuối cùng trên chiều thứ ba
print("Hai phần tử cuối cùng trên chiều thứ ba:")
print(a[:, :, -2:])



Shape của a: torch.Size([3, 4, 5])
Shape của a[1]: torch.Size([4, 5])
Shape của a[1:, 2:4]: torch.Size([2, 2, 5])
Hai phần tử cuối cùng trên chiều thứ ba:
tensor([[[-2.1055,  0.6784],
         [-0.7521,  1.6487],
         [-0.5594, -0.7688],
         [-0.4974,  0.4396]],

        [[ 1.6806,  1.2791],
         [-0.2316,  0.0418],
         [-0.8712, -0.2234],
         [ 0.3057, -0.7746]],

        [[-0.6011,  0.3672],
         [ 1.4451,  0.8564],
         [ 0.5612, -0.4527],
         [ 0.0566,  0.4263]]])

## Bài 5. Reshape và Flatten

In [ ]:
import torch

torch.manual_seed(42)
a = torch.randn(3, 4)

print("Original:")
print(a)
print("Số phần tử ban đầu:", a.numel())

print("\nFlatten:")
flat = a.ravel()
print(flat)
print("Shape sau flatten:", flat.shape)
print("Số phần tử sau flatten:", flat.numel())

print("\nReshape to 3 x 2 x 2:")
r = a.reshape(3, 2, 2)
print(r)
print("Shape:", r.shape)
print("Số phần tử:", r.numel())

print("\nReshape to 2 x 6:")
r2 = a.reshape(2, 6)
print(r2)


Original:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
Số phần tử ban đầu: 12

Flatten:
tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674,  0.5349,  0.8094])
Shape sau flatten: torch.Size([12])
Số phần tử sau flatten: 12

Reshape to 3 x 2 x 2:
tensor([[[ 0.3367,  0.1288],
         [ 0.2345,  0.2303]],

        [[-1.1229, -0.1863],
         [ 2.2082, -0.6380]],

        [[ 0.4617,  0.2674],
         [ 0.5349,  0.8094]]])
Shape: torch.Size([3, 2, 2])
Số phần tử: 12

Reshape to 2 x 6:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617,  0.2674,  0.5349,  0.8094]])

## Bài 6. Phép toán và nhân ma trận

In [ ]:
import torch

torch.manual_seed(42)
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\na * b (nhân từng phần tử):")
print(a * b)

print("\na @ b.T (nhân ma trận):")
print(a @ b.T)
print("Shape của a @ b.T:", (a @ b.T).shape)


a:
tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
b:
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])

a + b:
tensor([[ 2.5449, -0.5092,  0.6961],
        [ 0.4977, -0.5880,  0.6230]])

a / b:
tensor([[ 0.1525, -0.2019,  0.5079],
        [ 0.8615, -2.0992, -0.2302]])

a^2:
tensor([[0.1134, 0.0166, 0.0550],
        [0.0531, 1.2608, 0.0347]])

a * b (nhân từng phần tử):
tensor([[ 0.7435, -0.0822,  0.1082],
        [ 0.0616, -0.6006, -0.1508]])

a @ b.T (nhân ma trận):
tensor([[ 0.7695,  0.3487],
        [ 1.1390, -0.6898]])
Shape của a @ b.T: torch.Size([2, 2])

## Bài 7. Các hàm thống kê trên Tensor

In [ ]:
import torch

torch.manual_seed(42)
a = torch.randn(3, 4)

print("a:")
print(a)

print("\nMean theo cột (dim=0):")
print(torch.mean(a, dim=0))

print("\nStandard deviation theo cột (dim=0):")
print(torch.std(a, dim=0))

print("\nCumulative sum theo dim=0:")
print(torch.cumsum(a, dim=0))

print("\nMean theo hàng (dim=1):")
print(torch.mean(a, dim=1))

print("\nStandard deviation theo hàng (dim=1):")
print(torch.std(a, dim=1))

print("\nCumulative sum theo dim=1:")
print(torch.cumsum(a, dim=1))


a:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Mean theo cột (dim=0):
tensor([-0.1082,  0.0699,  0.9925,  0.1339])

Standard deviation theo cột (dim=0):
tensor([0.8810, 0.2325, 1.0635, 0.7285])

Cumulative sum theo dim=0:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-0.7862, -0.0575,  2.4427, -0.4077],
        [-0.3245,  0.2098,  2.9776,  0.4017]])

Mean theo hàng (dim=1):
tensor([0.2326, 0.0653, 0.5183])

Standard deviation theo hàng (dim=1):
tensor([0.0849, 1.4789, 0.2245])

Cumulative sum theo dim=1:
tensor([[ 0.3367,  0.4655,  0.7000,  0.9303],
        [-1.1229, -1.3092,  0.8990,  0.2610],
        [ 0.4617,  0.7290,  1.2639,  2.0733]])

## Bài 8. Autograd cơ bản

In [ ]:
import torch

# y = x^2
x = torch.tensor(3.6, requires_grad=True)
y = x * x
y.backward()

print("Trường hợp y = x^2")
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

# y = 3*x^2 + 2*x + 1
x2 = torch.tensor(3.6, requires_grad=True)
y2 = 3 * x2**2 + 2 * x2 + 1
y2.backward()

print("\nTrường hợp y = 3*x^2 + 2*x + 1")
print("x =", x2)
print("y =", y2)
print("x.grad =", x2.grad)


Trường hợp y = x^2
x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)

Trường hợp y = 3*x^2 + 2*x + 1
x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)

## Bài 9. Gradient Descent tìm hệ số đa thức

In [ ]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)
print("Final MSE:", mse.item())


Initial coefficients:
tensor([[0.3367],
        [0.1288],
        [0.2345]], requires_grad=True)
Learned coefficients:
tensor([[1.0087],
        [2.0033],
        [2.5330]], requires_grad=True)
Final MSE: 0.13043160736560822

## Bài 10. Giải hệ phương trình bằng Autograd

In [ ]:
import torch

torch.manual_seed(42)

A = torch.tensor(torch.rand(()).item(), requires_grad=True)
B = torch.tensor(torch.rand(()).item(), requires_grad=True)
C = torch.tensor(torch.rand(()).item(), requires_grad=True)
D = torch.tensor(torch.rand(()).item(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

print("\nKiểm tra:")
print("A + B =", (A+B).item())
print("C - D =", (C-D).item())
print("A + C =", (A+C).item())
print("B - D =", (B-D).item())
print("Tổng sai số bình phương =", sqerr.item())


A = 4.638497829437256
B = 4.361452102661133
C = 3.361468553543091
D = 2.361457109451294

Kiểm tra:
A + B = 8.999950408935547
C - D = 1.0000114440917969
A + C = 7.999966621398926
B - D = 1.9999949932098389
Tổng sai số bình phương = 3.729439868038753e-09

## Bài 11. Bài tập áp dụng

In [ ]:
import numpy as np
import torch

# 1. Tensor X có 24 phần tử và reshape
X = torch.arange(1, 25)

print("X ban đầu:", X)
print("4 x 6:")
print(X.reshape(4, 6))
print("2 x 12:")
print(X.reshape(2, 12))
print("2 x 3 x 4:")
print(X.reshape(2, 3, 4))

# 2. Hai Tensor A, B kích thước 3 x 4
torch.manual_seed(42)
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("\nA:")
print(A)
print("B:")
print(B)
print("A + B:")
print(A + B)
print("A * B:")
print(A * B)
print("A / B:")
print(A / B)
print("Trung bình theo cột:")
print(torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột:")
print(torch.std(A, dim=0))

# 3. y = 2x^2 + 5x + 3 tại x = 2
x = torch.tensor(2.0, requires_grad=True)
y = 2*x**2 + 5*x + 3
y.backward()

print("\ny = 2x^2 + 5x + 3")
print("y tại x=2:", y.item())
print("dy/dx bằng autograd:", x.grad.item())
print("dy/dx thủ công = 4x + 5 =", 4*2 + 5)

# 4. Huấn luyện đa thức y = 2x^2 - 3x + 5
np.random.seed(42)
torch.manual_seed(42)

N = 20
X_np = np.random.randn(N, 1) * 5
Y_np = 2 * X_np**2 - 3 * X_np + 5

XX = np.hstack([X_np**2, X_np, np.ones_like(X_np)])

w = torch.randn(3, 1, requires_grad=True)
x_train = torch.tensor(XX, dtype=torch.float32)
y_train = torch.tensor(Y_np, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x_train @ w
    mse = torch.mean((y_train - y_pred)**2)
    mse.backward()
    optimizer.step()

print("\nHệ số tìm được cho y = 2x^2 - 3x + 5:")
print(w)
print("Final MSE:", mse.item())


X ban đầu: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])
2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

A:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
B:
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])
A + B:
tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])